### ISSUE TITLE
Comunicación serial

### ISSUE THREAD

**Issue by gonzalpetraglia** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-laser-nivel#3]
Subimos, a metodo de prueba de la comunicación serial, para luego poder leer los valores devueltos por los sensores desde la PC, un programa chiquito que permite enviar desde el micro a la PC infinitamente el caracter 'a'. Queriamos confirmar que estaba bien, aunque ya vimos que funciona

**Comment by rarias** [comment]
ok, es la mejor prueba de que el código está bien.
Una sola cosa respecto al código, agreguen siempre como comentario al inicio, qué micro usan y a qué frecuencia.
Slds
