### ISSUE TITLE
No funciona correctamente I2C

### ISSUE THREAD

**Issue by PatricioIribarneCatella** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-laser-nivel#6]
- Se establece la comununicación.
- Puede leer varios bytes.
- Los bytes recibidos, parecen ser todos cero.

**Comment by PatricioIribarneCatella** [comment]
Se utiliza el _Arduino MEGA-2560_ de 16Mhz

**Comment by rarias** [comment]
Es prácticamente imposible de seguir su código, abusan del "CALL".   Les pasé un código "plano" probado, pueden hacer una prueba sencilla y ver si logran hacerlo andar?

**Comment by PatricioIribarneCatella** [comment]
Si esa prueba la hicimos y anda, con lo cual se puede descartar un problema en el circuito. Dentro del archivo **i2c.S** se encuentra definida la función `i2c_init` que realiza lo mismo que el código que nos pasaste (y esa parte funciona también). Solamente está dividida en distitntas funciones para poder utilizarlas luego en la lectura de cada uno de los bytes para obtener la acelaración y la inclinación. Lo que no nos anda es realizar la lectura de esos sucesivos bytes.

**Comment by PatricioIribarneCatella** [comment]
Acabo de encontrar el problema! Por _default_ el **sensor viene apagado**. Hay un registro en particular, el `0x6B` que tiene un bit que es de _sleep-mode_ y viene en 1, indicando que arranca en ese modo. Hay que escribirlo con un 0 para que se prenda el sensor. Subí en la carpeta de _hojas de datos_ el _register-map_ donde aclara todo esto.

Por eso podía leer bien el valor de `WHO_AM_I` pero leía todos ceros (valor por defalut de todos los registros) en los demás bytes.

Luego, vamos a estar agregando ese código para realizar la escritura correspondiente en ese registro, en la función de inicialización.
