### ISSUE TITLE
Motor stepper y driver

### ISSUE THREAD

**Issue by PatricioIribarneCatella** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-laser-nivel#8]
En la _pull-request_ #7 se agregaron los _data-sheets_ de el motor y el driver. Por lo que entendimos  tiene una reducción de 1:64 con lo cual utilizando _half-steps_ se podría llegar a 512 pasos, lo que daría un ángulo de 0.70. También, parece que habría que utilizar una fuente externa de 5v para no dañar el _arduino_. Queríamos saber si eso es correcto.

**Comment by rarias** [comment]
Si la corriente que mueve al motor es muy baja, digamos 100 a 250mA se podría usar la misma fuente.
